# The nickname of the bot, this can either be a string or a list
# When this is a string, if there is a nickname conflict the next nickname
# tried is the previous nickname plus an underscore, meanwhile if it is a
# list it runs through each nickname in the list and falls back to the
# string behavior on the last one.
nickname: "Ascultone"

# The username of the bot, nothing special about it.
username: "AscultoneBot"

# The real name of the bot, while normally this would be the real name of the person, there is no real meaningful (or default) value for this.
realname: "Ascultone IRC Bot"

# The hostname of the server to connect to.
hostname: "irc.hostname.tld"

# The port of the server to connect to.
# This is generally 6667 for insecure connections and 6697 if you wanna use
# TLS/SSL.
port: 6667

# The list of channels to automatically join. (WARNING: The channel names MUST
# be wrapped in double quotes)
channels:
    - "#channel"
    - "#channel2"

# The quit message that appears once the bot crashes/is closed via SIGINT
quit_message: "Seeya!"

# Where to store persistent information about Ascultone, you can just set this
# to ":memory:" if you don't want him to store anything between runs.
database: "ascultone.db"

# The configuration for the logging module.
# This is passed directly to `logging.basicConfig`.
logging:
    level: 20  # INFO
    format: "[%(asctime)s @ %(name)s %(levelname)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

# The list of modules to load. (Further info can be found in README.md)
modules:
    - "modules/greeter.py"
    - "modules/stomach.py"

module_config:
    greeter:
        on_self_join_messages:
            - "jumps in!"
            - "slides into the room!"
        on_other_join_messages:
            - "sits on {user}"
            - "throws pebbles at {user}"
            - "doesn't notice that {user} joined"
    stomach:
        stomach_message: "is digesting {victims}..."

