---

# The nickname of the bot, this can either be a string or a list
# When this is a string, if there is a nickname conflict the next nickname
# tried is the previous nickname plus an underscore, meanwhile if it is a
# list it runs through each nickname in the list and falls back to the
# string behavior on the last one.
nickname: "Ascultone"

# The username of the bot, nothing special about it.
username: "AscultoneBot"

# The real name of the bot, while normally this would be the real name
# the person, there is no real meaningful (or default) value for this.
realname: "Ascultone IRC Bot"

# The hostname of the server to connect to.
hostname: "irc.editingarchive.com"

# The port of the server to connect to.
# This is generally 6667 for insecure connections and 6697 if you wanna use
# TLS/SSL.
port: 6667

# The list of channels to automatically join. (WARNING: The channel names MUST
# be wrapped in double quotes)
channels:
    - "#bottest"

# The quit message that appears once the bot crashes/is closed via SIGINT
quit_message: "Seeya!"

# Where to store persistent information about Ascultone, you can just set this
# to ":memory:" if you don't want him to store anything between runs.
database: "ascultone.db"

# The configuration for the logging module.
# This is passed directly to `logging.basicConfig`.
logging:
    level: 20  # INFO
    format: "[%(asctime)s @ %(name)s %(levelname)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

flags:
    exampleNick:
        - "whitelisted"

    exampleAdmin:
        - "admin"

    exampleMultiple:
        - "admin"
        - "nogreet"

modules:
    # The list of modules to load, each item is passed to glob
    # (Further info can be found in README.md)
    files:
        - "modules/*.py"

    # Specific configuration for different modules
    config:
        greeter: {}
        stomach: {}
        attacker: {}

    # The different messages to use for the modules
    messages:
        greeter:
            greetings:
                - "welcomingly nuzzles and licks {nick}"
                - "welcomingly nuzzles {nick}"
                - "welcomingly licks {nick}"
                - "welcomingly tail-slaps {nick}"
                - "playfully nuzzles and licks {nick}"
                - "playfully nuzzles {nick}"
                - "playfully licks {nick}"
                - "playfully tail-slaps {nick}"
                - "tosses a pebble at {nick}"
                - "joyfully waggles his tail at {nick}'s arrival"
                - "cheerfully waggles his tail at {nick}'s arrival"
                - "playfully waggles his tail at {nick}'s arrival"
                - "welcomes {nick} with a cheerful warble"
            announce_arrival: "enters the arena!"
        stomach:
            stomach: "is digesting {victims}..."
            eat: "gulps down {victim}!"
            spit: "spits out {victim}!"
            spit_superfluous: "hasn't eaten {victim} yet!"
            vomit: "empties his stomach!"
            vomit_superfluous: "hasn't eaten anything yet!"
        attacker:
            attacks:
                - "shoots a plasma bolt at {target}!"
                - "hurls a pebble at {target}!"
                - "tackles {target}!"
                - "tail-whips {target}!"
                - "charges {target}!"
                - "unsheathes his teeth and bites {target}!"
        trigger_commands:
            learn: "has been trained by {nick}!"
            forget: "forgot one of his tricks!"
